import type { Place } from "./types";

export const mockPlaces: Place[] = [
  {
    placeId: 1,
    name: "BHV Marais",
    category: "MALL",
    address: "52 Rue de Rivoli, 75004",
    distanceText: "102m",
    latitude: 48.8575,
    longitude: 2.3546,
    acStatus: "AVAILABLE",
    trustScore: 92,
    totalReportCount: 2,
    lastReportedAt: "30min ago",
    mapX: 18,
    mapY: 18
  },
  {
    placeId: 2,
    name: "Shakespeare and Co.",
    category: "CAFE",
    address: "37 Rue de la Bucherie, 75005",
    distanceText: "581m",
    latitude: 48.8527,
    longitude: 2.3472,
    acStatus: "AVAILABLE",
    trustScore: 88,
    totalReportCount: 2,
    lastReportedAt: "2d ago",
    mapX: 54,
    mapY: 37
  },
  {
    placeId: 3,
    name: "Forum des Halles",
    category: "MALL",
    address: "101 Porte Berger, 75001",
    distanceText: "749m",
    latitude: 48.8625,
    longitude: 2.3448,
    acStatus: "AVAILABLE",
    trustScore: 76,
    totalReportCount: 3,
    lastReportedAt: "22min ago",
    mapX: 83,
    mapY: 59
  },
  {
    placeId: 4,
    name: "Le Marais Bistro",
    category: "RESTAURANT",
    address: "32 Rue de Bretagne, 75003",
    distanceText: "897m",
    latitude: 48.8639,
    longitude: 2.3613,
    acStatus: "AVAILABLE",
    trustScore: 81,
    totalReportCount: 2,
    lastReportedAt: "56min ago",
    mapX: 22,
    mapY: 72
  },
  {
    placeId: 5,
    name: "Cafe Procope",
    category: "CAFE",
    address: "13 Rue de l'Ancienne Comedie, 75006",
    distanceText: "1.1km",
    latitude: 48.8521,
    longitude: 2.3388,
    acStatus: "UNAVAILABLE",
    trustScore: 64,
    totalReportCount: 1,
    lastReportedAt: "380d ago",
    mapX: 25,
    mapY: 74
  },
  {
    placeId: 6,
    name: "Cafe de Flore",
    category: "CAFE",
    address: "172 Bd Saint-Germain, 75006",
    distanceText: "1.4km",
    latitude: 48.8541,
    longitude: 2.3322,
    acStatus: "UNVERIFIED",
    trustScore: 0,
    totalReportCount: 0,
    lastReportedAt: null,
    mapX: 64,
    mapY: 28
  }
];
